### PR TITLE
Dependency Fix for Magic Bees

### PR DESCRIPTION
**Pull request by Shibva**
TL;DR: updated workspace dependencies with the discontiuation of jitpack; should fix the issue 

Changes:
* Updated Build script to version as of 12/25/22
* spotless sorted (spotlessApply)
* **replaced MagicBees dependency to use the MagicBees:2.5.15-GTNH API**
* removed jitpack.yml now that it's not used period ("cleanup")

* Ensure that this pull request is going to GTNH space and not bart's [seriously, whose fucking idea at github was it to have a pull request by default refer to the origin of the fork instead of the fork your wanting to get the pull request from 💢 )

### CODE REVIEW

**Comment by Shibva** [comment]
Ive decided to push this as a seperate pull before I start working on stuff, figured to get this fixed to avoid others from having to repeat it; this WAS nessisary because of a compile error caused from MagicBees no longer being refrenced properly (as of a result of "jitpack" being discontinued in the Marven and rendering the method used as NULL

Thanks @mitchej123#0313 for helping me fix this ^w^

**Comment by Shibva** [comment]
why the hell is the check failing, I ensure I ran both the updating buildscript and the spotless

**Comment by kuba6000** [comment]
> why the hell is the check failing, I ensure I ran both the updating buildscript and the spotless

```2022-12-26T09:25:05.1551249Z A problem occurred evaluating root project 'WitchingGadgets'.```

Please run any gradle task locally and push newly created files.

**Comment by Shibva** [comment]
> > why the hell is the check failing, I ensure I ran both the updating buildscript and the spotless
> 
> Please run any gradle task locally and push newly created files.

eh? can ya elaborate? in fact maybe gibe me rundown on the steps I need todo, clearly im missing some things and it be better if I know than trying to figure it out

**Comment by kuba6000** [comment]
> > > why the hell is the check failing, I ensure I ran both the updating buildscript and the spotless
> > 
> > Please run any gradle task locally and push newly created files.
> 
> eh? can ya elaborate? in fact maybe gibe me rundown on the steps I need todo, clearly im missing some things and it be better if I know than trying to figure it out

You should have 2 new uncomitted files locally settings.gradle and .gitattributes. Just commit them and push

**Comment by Shibva** [comment]
OOOOOOH
thats why, I thought those were genertated for my workspace only

Thanks

**Comment by Shibva** [comment]
closing pull to have everything be done on a fresh instance

**Pull request closed without merging**
