### PR TITLE
Fix the Ageing stone

### PR DESCRIPTION
**Pull request by Ethryan**
For how long has this been broken?????

### CODE REVIEW

**Review by OneEyeMaker — APPROVED** [review]

**Comment by Alastors** [comment]
What's it supposed to do again?

**Comment by Ethryan** [comment]
Its the speed up growing of animals/entities. IE Villagers and Animals.

**Comment by Alastors** [comment]
Ahhhh, I think that's been broken awhile now

**Comment by Ethryan** [comment]
Think I got it fixed now.

**Pull request merged**
