### PR TITLE
Primordial Armor's repairing Fix & Buff

### PR DESCRIPTION
**Pull request by Sheodar**
Fixes:
- Fixed armor's reapiring. Removed custom `tickcounter` and replaced to forge's API `EntityPlayer.ticksExisted`.

Balance changes:
- Buffed repairing from 1/5sec (theorically, but it works never) to 1/1sec. 
  - Reasons: we have 3 levels of magical armors: Thaum > Shadow > Primordial. And Thaum Cuirass have more regen then Primordial (Thaum has 1 regen per sec).

### CODE REVIEW

**Comment by Sheodar** [comment]
There is no updated GTNH-Unoffficail version dependencies in gradle.dependencies

**Comment by Dream-Master** [comment]
@Sheodar try to run update buildscript, spotless and update dependencies

**Comment by Dream-Master** [comment]
include my dev brannch and it should build @Sheodar

**Comment by Sheodar** [comment]
@Dream-Master github bot doesn't see this commits. Dependencies was updated and build was successfully too

**Comment by chochem** [comment]
I dont understand the premise here. why are you trying to buff primordial? its already widely considered op. well terra affinity is for sure.

**Comment by Sheodar** [comment]
> I dont understand the premise here. why are you trying to buff primordial? its already widely considered op. well terra affinity is for sure.

For first this repairing worked never, it is just broken. For second it crafts from thaumic cuirass and it has 1/1sec repairing. It is just extended behavior.

**Comment by chochem** [comment]
eh that sounds fine. just letting you know that primordial has way more regen than thaum cuirass. Well its really a bug I suppose we should fix at some point.

**Comment by Dream-Master** [comment]
> @Dream-Master github bot doesn't see this commits. Dependencies was updated and build was successfully too

yes because i updated it :)

**Comment by chochem** [comment]
I had to press the run button :P

**Review by Alastors — APPROVED** [review]

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
